-- ================================
-- FULFILLMENT WORKER SEED DATA
-- Generated by seed-fulfillment.mjs
-- ================================

-- STEP 1: Postal Code Warehouse Map (generated first)
-- This defines which warehouses serve which postal codes

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_b4c74ae9',
      '400001',
      '400099',
      'Maharashtra',
      'Mumbai Metro',
      '[{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":1},{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_67955112',
      '400100',
      '400199',
      'Maharashtra',
      'Mumbai Metro',
      '[{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":1},{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_f0b71565',
      '110001',
      '110099',
      'Delhi',
      'Delhi NCR',
      '[{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_e8ca8dc3',
      '110100',
      '110199',
      'Delhi',
      'Delhi NCR',
      '[{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_73a5313a',
      '560001',
      '560099',
      'Karnataka',
      'Bangalore Metro',
      '[{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_394b0716',
      '560100',
      '560199',
      'Karnataka',
      'Bangalore Metro',
      '[{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_78a20432',
      '600001',
      '600099',
      'Tamil Nadu',
      'Chennai Metro',
      '[{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_afe12217',
      '600100',
      '600199',
      'Tamil Nadu',
      'Chennai Metro',
      '[{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_f7666557',
      '700001',
      '700099',
      'West Bengal',
      'Kolkata Metro',
      '[{"warehouse_id":"wh_005","name":"Kolkata East Warehouse","base_days":1},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_37ea6299',
      '700100',
      '700199',
      'West Bengal',
      'Kolkata Metro',
      '[{"warehouse_id":"wh_005","name":"Kolkata East Warehouse","base_days":1},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_b7356504',
      '500001',
      '500099',
      'Telangana',
      'Hyderabad Metro',
      '[{"warehouse_id":"wh_006","name":"Hyderabad North Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_8774097f',
      '500100',
      '500199',
      'Telangana',
      'Hyderabad Metro',
      '[{"warehouse_id":"wh_006","name":"Hyderabad North Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_9dcbea0b',
      '411001',
      '411099',
      'Maharashtra',
      'Pune Metro',
      '[{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_e8c5633a',
      '411100',
      '411199',
      'Maharashtra',
      'Pune Metro',
      '[{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_3a864d6b',
      '380001',
      '380099',
      'Gujarat',
      'Ahmedabad Metro',
      '[{"warehouse_id":"wh_008","name":"Ahmedabad Central Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]'
    );

INSERT OR IGNORE INTO postal_code_warehouse_map (
      mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses
    ) VALUES (
      'map_bc3ce471',
      '380100',
      '380199',
      'Gujarat',
      'Ahmedabad Metro',
      '[{"warehouse_id":"wh_008","name":"Ahmedabad Central Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]'
    );

-- STEP 3: Delivery Cost Config
-- Delivery cost tiers for different warehouse distances

DELETE FROM delivery_cost_config WHERE tier_name IN ('tier_1', 'tier_2', 'tier_3');

INSERT INTO delivery_cost_config (
      config_id, tier_name, tier_description,
      standard_delivery_cost, express_delivery_cost,
      free_delivery_threshold, currency
    ) VALUES (
      'cost_tier_1',
      'tier_1',
      'Nearest warehouse (1-2 days)',
      0,
      99,
      2999,
      'INR'
    );

INSERT INTO delivery_cost_config (
      config_id, tier_name, tier_description,
      standard_delivery_cost, express_delivery_cost,
      free_delivery_threshold, currency
    ) VALUES (
      'cost_tier_2',
      'tier_2',
      'Regional warehouse (2-3 days)',
      49,
      149,
      2999,
      'INR'
    );

INSERT INTO delivery_cost_config (
      config_id, tier_name, tier_description,
      standard_delivery_cost, express_delivery_cost,
      free_delivery_threshold, currency
    ) VALUES (
      'cost_tier_3',
      'tier_3',
      'Distant warehouse (3-4 days)',
      99,
      249,
      2999,
      'INR'
    );