-- ================================
-- POSTAL CODE MAP (ONLY)
-- Generated by scripts/seed-postal-map.mjs
-- Safe to re-run: deletes existing rows for affected (state, region) and reinserts merged ranges
-- ================================

DELETE FROM postal_code_warehouse_map WHERE state='Maharashtra' AND region_name='Mumbai Metro';
DELETE FROM postal_code_warehouse_map WHERE state='Delhi' AND region_name='Delhi NCR';
DELETE FROM postal_code_warehouse_map WHERE state='Karnataka' AND region_name='Bangalore Metro';
DELETE FROM postal_code_warehouse_map WHERE state='Tamil Nadu' AND region_name='Chennai Metro';
DELETE FROM postal_code_warehouse_map WHERE state='West Bengal' AND region_name='Kolkata Metro';
DELETE FROM postal_code_warehouse_map WHERE state='Telangana' AND region_name='Hyderabad Metro';
DELETE FROM postal_code_warehouse_map WHERE state='Maharashtra' AND region_name='Pune Metro';
DELETE FROM postal_code_warehouse_map WHERE state='Gujarat' AND region_name='Ahmedabad Metro';
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_fa9f2ec4','400001','400199','Maharashtra','Mumbai Metro','[{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":1},{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_c49a3778','110001','110199','Delhi','Delhi NCR','[{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_4f907e59','560001','560199','Karnataka','Bangalore Metro','[{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_69cea0a4','600001','600199','Tamil Nadu','Chennai Metro','[{"warehouse_id":"wh_004","name":"Chennai Central Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_0030f2a6','700001','700199','West Bengal','Kolkata Metro','[{"warehouse_id":"wh_005","name":"Kolkata East Warehouse","base_days":1},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_35e2eb40','500001','500199','Telangana','Hyderabad Metro','[{"warehouse_id":"wh_006","name":"Hyderabad North Warehouse","base_days":1},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":2},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_04bacb98','411001','411199','Maharashtra','Pune Metro','[{"warehouse_id":"wh_007","name":"Pune West Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":3},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":4}]');
INSERT INTO postal_code_warehouse_map (mapping_id, start_postal_code, end_postal_code, state, region_name, warehouses)
VALUES ('map_f495d0df','380001','380199','Gujarat','Ahmedabad Metro','[{"warehouse_id":"wh_008","name":"Ahmedabad Central Warehouse","base_days":1},{"warehouse_id":"wh_001","name":"Mumbai Central Warehouse","base_days":2},{"warehouse_id":"wh_002","name":"Delhi North Warehouse","base_days":3},{"warehouse_id":"wh_003","name":"Bangalore Tech Warehouse","base_days":4}]');
